# -*- coding: utf-8 -*-
"""Visdat_Bokeh_Group 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11zrdtU4nUYvgo--CINTJsKtTNxSPvvqz

**GROUP 5**

Anggota:


*   Muhammad Bayu Samudera S. (1301194031)
*   Muhammad Attalariq (1301194294)
*   Irgi Aditya Rachman (1301194391)
"""

# Import libraries

import pandas as pd
import numpy as np

from bokeh.io import output_file, output_notebook,curdoc
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource
from bokeh.layouts import row, column, gridplot
from bokeh.models.widgets import Tabs, Panel

from bokeh.core.validation import silence
from bokeh.core.validation.warnings import EMPTY_LAYOUT, MISSING_RENDERERS
silence(EMPTY_LAYOUT, True)
silence(MISSING_RENDERERS, True)

curdoc().theme = "dark_minimal"

df_HangSeng = pd.read_csv("./Hang_Seng.csv")

df_NasDaq = pd.read_csv("./Nasdaq.csv")

df_Nikkei = pd.read_csv("./Nikkei.csv")

df_Nikkei['Date'] = pd.to_datetime(df_Nikkei['Date'])
df_NasDaq['Date'] = pd.to_datetime(df_NasDaq['Date'])
df_HangSeng['Date'] = pd.to_datetime(df_HangSeng['Date'])

p = figure(title='Hang Seng In Stock Market',
           x_axis_label='Month-Year', y_axis_label='Price',
           x_axis_type='datetime',
           sizing_mode="stretch_width", plot_height=350)

p.line(x=df_HangSeng['Date'], y=df_HangSeng['Adj Close'], line_width=2, line_color="cyan")

p = figure(title='NasDaq In Stock Market',
           x_axis_label='Month-Year', y_axis_label='Price',
           x_axis_type='datetime',
           sizing_mode="stretch_width", plot_height=350)

p.line(x=df_NasDaq['Date'], y=df_NasDaq['Adj Close'], line_width=2, line_color="orange")

p = figure(title='Nikkei In Stock Market',
           x_axis_label='Month-Year', y_axis_label='Price',
           x_axis_type='datetime',
           sizing_mode="stretch_width", plot_height=350)

p.line(x=df_Nikkei['Date'], y=df_Nikkei['Adj Close'], line_width=2, line_color="blue")

HangSeng_cds = ColumnDataSource(df_HangSeng)
NasDaq_cds = ColumnDataSource(df_NasDaq)
Nikkei_cds = ColumnDataSource(df_Nikkei)

df_HangSeng['image'] = 'https://www.logolynx.com/images/logolynx/b5/b58776ed2b1aa648ad97051fbc53457.jpeg'
df_NasDaq['image'] = 'https://amcham.no/wp-content/uploads/2019/04/nasdaq-logo-white.png'
df_Nikkei['image'] = 'https://cdn.shopify.com/s/files/1/1548/2107/files/nikkei.png?v=1480953545'

from bokeh.layouts import layout
from bokeh.models import HoverTool,Select
from bokeh.models import CustomJS

hover = HoverTool(tooltips="""
                  <div>
                    <div><strong>Adj Close:</strong>@{Adj Close}</div>
                    <br>
                    <div><img src="@image" alt="@Name" width="200" /><div>
                  </div>   
                  """)

TOOLTIPS="""
      <div>
        <div><strong>Adj Close:</strong>@{Adj Close}</div>
        <br>
        <div><img src="@image" alt="@Name" width="200" /><div>
      </div>
        
"""

TOOLTIPS2="""
      <div>
        <div><strong>Volume:</strong>@{Adj Close}</div>
        <br>
        <div><img src="@image" alt="@Name" width="200" /><div>
      </div>

"""

fig = figure(title='STOCK MARKET',
             x_axis_label='Month-Year', y_axis_label='Price',
             x_axis_type='datetime',
             sizing_mode="stretch_width", plot_height=350)

points = fig.line(x='Date', y='Adj Close', source=HangSeng_cds, legend_label="HangSeng", line_width=2, line_color="cyan")
points2 = fig.line(x='Date', y='Adj Close', source=NasDaq_cds, legend_label="NasDaq", line_width=2, line_color="red")
points3 = fig.line(x='Date', y='Adj Close', source=Nikkei_cds, legend_label="Nikkei", line_width=2, line_color="green")

select = Select(title="Choose Parameter", value=points.glyph.y, options=['Adj Close', 'Volume'])
select.js_on_change('value',
                    CustomJS(args=dict(other1=fig, hover=hover, TOOLTIPS=TOOLTIPS, TOOLTIPS2=TOOLTIPS2, fig=fig.tools, points=points, points2=points2, points3=points3, new_y={}),
                    code="""
                        new_y = {'field':this.value}
                        points.glyph.y = new_y
                        points2.glyph.y = new_y
                        points3.glyph.y = new_y

                        if(this.value == 'Adj Close'){
                          console.log('Change hover to :', this.value)
                          fig[6].tooltips = TOOLTIPS
                        }else if(this.value == 'Volume'){
                          console.log('Change hover to :', this.value)
                          fig[6].tooltips = TOOLTIPS2
                        }
                        console.log(new_y)

                    """
                    )
                  )

def set_style(p):
  # Tick labels
  p.xaxis.major_label_text_font_size = '6pt'
  p.yaxis.major_label_text_font_size = '10pt'

fig1 =figure(title='Nikkei In Stock Market',
           x_axis_label='Month-Year', y_axis_label='Price',
           x_axis_type='datetime',
           sizing_mode="stretch_width", plot_height=350,plot_width=750)
fig1.line(x=df_Nikkei['Date'], y=df_Nikkei['Adj Close'], line_width=2, line_color="blue")
tab1 = Panel(child=fig1, title="Nikkei")

fig2 =figure(title='NasDaq In Stock Market',
           x_axis_label='Month-Year', y_axis_label='Price',
           x_axis_type='datetime',
           sizing_mode="stretch_width", plot_height=350,plot_width=750)
fig2.line(x=df_NasDaq['Date'], y=df_NasDaq['Adj Close'], line_width=2, line_color="cyan")
tab2 = Panel(child=fig2, title="NasDaq")

tabs = Tabs(tabs=[ tab1, tab2])

set_style(fig1)
set_style(fig2)

fig.add_tools(hover)

fig.title.text_font_size= "25px"
fig.title.align="right"
fig.title.text_color="white"

fig.legend.label_text_font="times"
fig.legend.label_text_font_style="italic"

fig.legend.background_fill_color="black"
fig.legend.background_fill_alpha=0.8

fig.legend.click_policy="hide"

layout=layout([
               [tabs],
               [select],
               [fig],
])

curdoc().add_root(layout)
curdoc().title = "Stock Market Visualization"
